Resonite~/ResoniteHook/Launcher/Launcher.cs
Resonite~/ResoniteHook/Launcher/SteamUtils.cs

Since I do not have devices running other operating systems, I have only tested the functionality on the Windows platform.

feat: automatic detection of game install paths

---

Resonite~/ResoniteHook/.gitignore
Resonite~/ResoniteHook/Launcher/Launcher.cs
Resonite~/ResoniteHook/Launcher/Launcher.csproj
Resonite~/ResoniteHook/Puppeteer/EngineInterface.cs
Resonite~/ResoniteHook/Puppeteer/Program.cs
Resonite~/ResoniteHook/Puppeteer/TickController.cs
Resonite~/ResoniteHook/Puppeteer/conversion/MeshTranslator.cs
Resonite~/ResoniteHook/Puppeteer/rpc/EntryPoint.cs
Resonite~/ResoniteHook/PuppeteerTests/PuppeteerTests.csproj
Resonite~/ResoniteHook/PuppeteerTests/UnitTest1.cs
Resonite~/ResoniteHook/PuppeteerTests/testsrc/MeshXConversionTests.cs
Resonite~/ResoniteHook/PuppeteerTests/testsrc/TestBase.cs
Resonite~/ResoniteHook/PuppeteerTests/testsrc/VerifyEngineOperational.cs
Resonite~/ResoniteHook/ResoniteHook.sln

fix: duplicate blendshapes break the build

---

Editor/BuildController.cs
Editor/RPCClientController.cs
Editor/UI/ResoniteBuildUI.cs

fix: timeouts during build can cause backend to shut down

---

Resonite~/ResoniteHook/Puppeteer/conversion/Dynamics.cs

fix: implicit root PBs fail to build

---

Resonite~/ResoniteHook/Puppeteer/conversion/AvatarSetup.cs

fix: incorrect viewpoint position

---

Editor/SerializeAvatar/AvatarSerializer.cs
Resonite~/ResoniteHook/Puppeteer/conversion/RootConverter.cs
Resonite~/ResoniteHook/ResoPuppetSchema/proto/asset.proto

fix: texture import size and normal map settings aren't respected

---

package.json

chore: add license field to package manifest

---

Resonite~/ResoniteHook/Puppeteer/ResoNamespaces.cs
Resonite~/ResoniteHook/Puppeteer/conversion/AvatarSetup.cs
Resonite~/ResoniteHook/Puppeteer/conversion/Context.cs
Resonite~/ResoniteHook/Puppeteer/conversion/Dynamics.cs
Resonite~/ResoniteHook/Puppeteer/conversion/Material.cs
Resonite~/ResoniteHook/Puppeteer/conversion/RigNaming.cs
Resonite~/ResoniteHook/Puppeteer/conversion/RootConverter.cs
Resonite~/ResoniteHook/Puppeteer/filters/BoneAnnotationsFilter.cs
Resonite~/ResoniteHook/Puppeteer/filters/EyeSwingVariableFilter.cs
Resonite~/ResoniteHook/Puppeteer/filters/FaceMeshReferenceFilter.cs
Resonite~/ResoniteHook/Puppeteer/filters/HandIsolationFilter.cs
Resonite~/ResoniteHook/Puppeteer/filters/MeshLoadingFilter.cs
Resonite~/ResoniteHook/Puppeteer/filters/ThumnailAssetProviderFilter.cs

NOTE: This change changes the dynvar namespaces used by MA; this means that settings will have to be manually copied over this time.
Closes: #46

feat: additional annotations

---

Resonite~/ResoniteHook/Puppeteer/conversion/AvatarSetup.cs
Resonite~/ResoniteHook/Puppeteer/filters/RenderSettingsFilter.cs

feat: add an AvatarRenderSettings settings node

---

Editor/DotNetCheck.cs
Editor/DotNetCheck.cs.meta
Editor/UI/DotNetInstallWindow.cs
Editor/UI/DotNetInstallWindow.cs.meta
Editor/UI/ResoniteBuildUI.cs
Editor/UI/Resources/DotNetCheck.uxml
Editor/UI/Resources/DotNetCheck.uxml.meta

feat: add .NET 9 install guidance

---

Resonite~/ResoniteHook/Puppeteer/CloudSpawnAssets.cs
Resonite~/ResoniteHook/Puppeteer/Program.cs
Resonite~/ResoniteHook/Puppeteer/ResoNamespaces.cs
Resonite~/ResoniteHook/Puppeteer/conversion/AvatarSetup.cs
Resonite~/ResoniteHook/Puppeteer/filters/AvatarPoseNodeRefFilter.cs
Resonite~/ResoniteHook/Puppeteer/filters/MeshLoadingFilter.cs

Also adds persistent dynvar refs to AvatarPoseNodes.

feat: show user thumbnail when avatar is loading

---

Resonite~/ResoniteHook/Puppeteer/conversion/AvatarSetup.cs
Resonite~/ResoniteHook/Puppeteer/filters/MiscRefFilter.cs

feat: create "Avatar" DV space

---

Resonite~/ResoniteHook/Puppeteer/conversion/Material.cs

fix: always import materials with ZWrite on

---

Resonite~/ResoniteHook/Puppeteer/conversion/AvatarSetup.cs

Handling isn't perfect yet; in particular, the desktop hand poses are a bit off. This needs testing in VR as well.
Closes: #15

feat: improve handling of A-pose avatars

---

Resonite~/ResoniteHook/Puppeteer/conversion/AvatarSetup.cs

fix: toolshelf is placed underneath the right hand

---

Editor/SerializeAvatar/AvatarSerializer.cs
Resonite~/ResoniteHook/Puppeteer/conversion/AvatarSetup.cs
Resonite~/ResoniteHook/Puppeteer/conversion/RigNaming.cs

fix: extra children of finger bones can break finger rig detection

---

Resonite~/ResoniteHook/Puppeteer/conversion/AvatarSetup.cs

fix: tool anchor and viewpoint orientation issues in some avatars

---

Resonite~/ResoniteHook/Puppeteer/CloudSpawnAssets.cs

- Fix: AvatarWorn detection breaks when culling systems are active
- Fix: Loading display size depends on the orientation of your head

chore: update cloud spawn assets

---

Resonite~/ResoniteHook/Puppeteer/conversion/MeshTranslator.cs

Works around bug: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/4547
Closes: #125

fix: workaround Resonite bug breaking mesh loading

---

Resonite~/ResoniteHook/Puppeteer/conversion/AvatarSetup.cs
Resonite~/ResoniteHook/Puppeteer/conversion/Helpers.cs

Also fixes an issue where sometimes fingers would not be detected appropriately.
Closes: #119

fix: poor hand orientation selection when fingers are not detected

---

Resonite~/ResoniteHook/Puppeteer/filters/MeshLoadingFilter.cs

fix: renderers with null meshes in unity cause the avatar to never finish loading

---

Resonite~/ResoniteHook/Puppeteer/ResoNamespaces.cs
Resonite~/ResoniteHook/Puppeteer/conversion/AvatarSetup.cs
Resonite~/ResoniteHook/Puppeteer/filters/VRIKFixupsFilter.cs

feat: add DynVar for VRIK.HeadMaxFixDistance

---

Editor/SerializeAvatar/AvatarSerializer.cs
Editor/UI/ResoniteBuildUI.cs
Resonite~/ResoniteHook/Puppeteer/ResoNamespaces.cs
Resonite~/ResoniteHook/Puppeteer/conversion/RootConverter.cs
Resonite~/ResoniteHook/ResoPuppetSchema/proto/objects.proto

feat: embed version info

---

Editor/SerializeAvatar/Dynamics.cs
package.json

Closes: #146
Related: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/4667

fix: exclude inside bounds colliders

---

Resonite~/ResoniteHook/Puppeteer/conversion/Dynamics.cs

fix: component enabled state for DynBones is not propagated properly

---

Resonite~/ResoniteHook/Puppeteer/ResoNamespaces.cs
Resonite~/ResoniteHook/Puppeteer/conversion/AvatarSetup.cs
Resonite~/ResoniteHook/Puppeteer/conversion/Dynamics.cs
Resonite~/ResoniteHook/Puppeteer/filters/DynBoneAutoEnableFilter.cs

feat: disable dynbones when all downstream meshes are disabled or missing

---

Editor/SerializeAvatar/Dynamics.cs
Resonite~/ResoniteHook/Puppeteer/conversion/Dynamics.cs
Resonite~/ResoniteHook/ResoPuppetSchema/proto/dynamics.proto

feat: improve DynBone bindings and defaults
Closes: #122

feat: improve DynBone bindings and defaults

---

Resonite~/ResoniteHook/Puppeteer/conversion/AvatarSetup.cs

We'll need to revisit this more later but for now index finger positioning doesn't feel great.

fix: adjust tooltip position

---

Resonite~/ResoniteHook/Puppeteer/filters/DynBoneAutoEnableFilter.cs

fix: NRE in DynBoneAutoEnableFilter

---

Resonite~/ResoniteHook/Puppeteer/TickController.cs
Resonite~/ResoniteHook/Puppeteer/conversion/AvatarSetup.cs
Resonite~/ResoniteHook/Puppeteer/conversion/Context.cs
Resonite~/ResoniteHook/Puppeteer/conversion/Dispatch.cs
Resonite~/ResoniteHook/Puppeteer/conversion/Dynamics.cs
Resonite~/ResoniteHook/Puppeteer/conversion/Material.cs
Resonite~/ResoniteHook/Puppeteer/conversion/MeshRenderer.cs
Resonite~/ResoniteHook/Puppeteer/conversion/RootConverter.cs
Resonite~/ResoniteHook/Puppeteer/filters/DynBoneAutoEnableFilter.cs
Resonite~/ResoniteHook/Puppeteer/filters/FirstPersonVisibleMeshProcessor.cs
Resonite~/ResoniteHook/Puppeteer/rpc/StatusStream.cs
Resonite~/ResoniteHook/PuppeteerCommon/LogListener.cs

Saving MeshX is very slow; avoid serializing meshes in the FPV filter more than needed.

perf: improve processing speed

---

Resonite~/ResoniteHook/Puppeteer/conversion/AvatarSetup.cs
Resonite~/ResoniteHook/Puppeteer/conversion/RigNaming.cs

Fixes: https://x.com/Lasairfhiona/status/1944426314074620412

fix: dynamic bones on toes breaks VRIK

---

Editor/ShaderSupport/LiltoonShaderSupport.cs
Resonite~/ResoniteHook/Puppeteer/conversion/Context.cs
Resonite~/ResoniteHook/Puppeteer/conversion/Material.cs
Resonite~/ResoniteHook/Puppeteer/filters/FirstPersonVisibleFilter.cs
Resonite~/ResoniteHook/ResoPuppetSchema/proto/asset.proto

fix: make lilToonFakeShadow invisible

---

Editor/SerializeAvatar/AvatarSerializer.cs
Editor/ShaderSupport/LiltoonBaker.cs
Editor/ShaderSupport/LiltoonShaderSupport.cs
Resonite~/ResoniteHook/Puppeteer/conversion/Context.cs
Resonite~/ResoniteHook/Puppeteer/conversion/Material.cs
Resonite~/ResoniteHook/ResoPuppetSchema/proto/asset.proto
Runtime/Shaders/BakeMetallicGlossReflectionMap.shader
Runtime/Shaders/BakeMetallicGlossReflectionMap.shader.meta

feat: add support for liltoon metallic/smoothness/reflectance

---

Editor/ShaderSupport/LiltoonShaderSupport.cs

[https://github.com/bdunderscore/modular-avatar-resonite/pull/182](url)
上記のPRで変数の名前にミスがあったので訂正して新しくPRさせて頂きました。
確認をお願いします。

Fix variable name `_Reflection` → `_ApplyReflection`
